### ISSUE TITLE
Display conduit hover is slow and wrong colour

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleRhino#115]
And laggy. Check with @PaulPoinet re speeding up/removing boxes.  
Colour, according to @fraguada should be the "speckle blue" :)

**Comment by didimitrie** [comment]
I'll pm you a big fat stream

**Comment by fraguada** [comment]
But it seems the laggyness is on the SpeckleView side of things, since it is accumulating and eventually processing mouseover events?

**Comment by didimitrie** [comment]
Yes indeed. I was just trying to capture the behaviour in a gif.

**Comment by didimitrie** [comment]
I'll stop, send you a big fat stream,  and the last layers are annoying. It think it can be potentially  debounced on the viewer side so as to send less events over...

**Comment by fraguada** [comment]
The color issue at least taken care of. @didimitrie mentioned we should debounce over events in [SpeckleView](https://github.com/speckleworks/SpeckleView/issues/2).

**Comment by PaulPoinet** [comment]
Not sure if it's today's problem but as far as I remember the issue was with the box edge corners. With a big stream, it starts to get very slow to display them as you need to calculate the bounding box for each object of the stream. I would suggest to get completely rid of them if it's not the case already

**Comment by didimitrie** [comment]
Somehow rhino sender clients now don't have the hover preview working. All of the above are solved (see speckleworks/SpeckleView#2)

**Comment by didimitrie** [comment]
I think this issue is superseeded by #178, and what it was initially raised for got fixed.
