### ISSUE TITLE
UI Conflicts

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleRhino#133]
![image](https://user-images.githubusercontent.com/7696515/36479972-840a1306-1702-11e8-9847-b542041cd3ed.png)
can't click on layer visibility

![image](https://user-images.githubusercontent.com/7696515/36480017-a9233078-1702-11e8-8195-689d150f8f1d.png)
can't click on "delete"

🥇

**Comment by fraguada** [comment]
The 'delete' issue seems to be solved as that card goes on top of the '+'. 
For the other issue, what about just having a footer, and the client buttons fly out to the left?

**Comment by didimitrie** [comment]
i was thinking something really easy, just add a `speckle-client` class to all receiver/sender containers and then drop a css rule `.speckle-client:last-child{ margin-bottom:  1000000px}`

**Comment by fraguada** [comment]
I has a similar thought. That would at least always keep some whitespace that can be scrolled to. Weird, but might work.

**Comment by didimitrie** [comment]
simple, and easy. i  don't think necessarily "weird"

**Comment by didimitrie** [comment]
fixed in speckleworks/SpeckleView#3
