### ISSUE TITLE
Allow manual refresh in Receivers

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleRhino#146]
- [x] Grasshopper - implement as context menu option
- [x] Rhino - see where to fit another button

**Comment by fraguada** [comment]
This is more of a SpeckleViewer issue, but if stream is paused, perhaps then the manual refresh button shoulld appear.
<img width="430" alt="screen shot 2018-03-25 at 10 31 17" src="https://user-images.githubusercontent.com/1014562/37873207-bd81ee0a-3017-11e8-89e7-0cb20888a207.png">

**Comment by fraguada** [comment]
Wait, we don't need this. Maybe I misunderstood, but when would this be needed in Rhino? Already in SpeckleView we get 'stream outdated' messages in receivers and senders. 🤦‍♂️ 
When would we need a manual refresh button in Rhino?

**Comment by didimitrie** [comment]
i've added a force refresh context menu option to the grasshopper components; we're good. i'll close
