### ISSUE TITLE
Speckle panel does not load UI

### ISSUE THREAD

**Issue by Crashnorun** [speckleworks/SpeckleRhino#147]
I've cloned the SpeckleRhino repo. To resolve some error I unloaded the RhinoMac and Rhino6 projects. I can build the SpeckleRhino project with no errors. When I load the RHP into rhino, the Speckle panel displays but no UI elements are visible. 
![image](https://user-images.githubusercontent.com/4449363/37484685-a0688cd0-285f-11e8-9070-98585b9e9465.png)
I've opened the CMD and navigated to the SpeckleRhinoView folder. I've run _npm run dev_ and a series of errors have displayed.
![image](https://user-images.githubusercontent.com/4449363/37484769-dff17114-285f-11e8-99c2-0eb6055c068e.png)

Any thoughts what I may be missing?

**Comment by didimitrie** [comment]
hey charlie! yes, an `npm install`

**Comment by fraguada** [comment]
I've updated the [README.md](https://github.com/speckleworks/SpeckleRhino/blob/master/README.md) and made a page on the wiki regarding the [Setup, Build, and Running procedures](https://github.com/speckleworks/SpeckleRhino/wiki/Develop-SpeckleRhino).
