### ISSUE TITLE
Grasshopper New Account Registration Fails

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleRhino#159]
as reported by @tsvilans 
![image](https://user-images.githubusercontent.com/7696515/38148394-46f92ace-344e-11e8-819e-e0d691ab9c94.png)

Coupled with this, I  can't seem to be able to debug the popup properly :(

**Comment by TTWDmitryZelenkin** [comment]
Have the same problem when compile from sources.

**Comment by didimitrie** [comment]
I would really want to get rid of this completely. Not sure how to go about it, ideas are welcome...

**Comment by tsvilans** [comment]
Will try with Rhino 5 when I get some time... Haven't had the chance to look at the code for this.

**Comment by radumg** [comment]
getting this with Rhino5 x64 too - have we tracked down where the issue is yet ? I could try to squash the bug if so.

**Comment by didimitrie** [comment]
Figured it out. For one reason or the other, the popup was an ancient nuget reference, and not the project itself. 

This is now fixed, and updated to use 1.0.0, and the popup is redesigned.
