### ISSUE TITLE
Remove Default Settings for JsonConvert

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleRhino#162]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour

json convert to work without errors 

#### Actual Behaviour

Setting the default settings on json convert (in `interop.cs` ctor) affects other plugin's behaviour if they rely on jsonconvert. Not cool!

#### Proposed Solution (if any)

Remove the dependecy on default settings by having a publicly available  cross speckle plugin instance of `JsonSerializerSettings` with the camel case contract resolver.

**Comment by fraguada** [comment]
🤔 should this go lower into SpeckleCore?

**Comment by didimitrie** [comment]
nope. this really has to do with the default serialisation settings set up `interop.cs`;
though now i'm doing extra debugging (with SpeckleRhino unloaded) and that error is replaced by others.

**Comment by didimitrie** [comment]
Well interop is  just for speckle rhino at the moment, no?

**Comment by mswaidan** [comment]
I _think_ this issue is related to one I'm bumping into? Same object has some JSON keys changed when I'm using my local builds of SpeckleGrasshopper.gha

SpeckleGrasshopper.gha from AppVeyor build JSON:
```
xdir: {
type: "Vector",
value: [ -0.865788603160596, 0.5004099265974089, 0 ],
hash: "1fa33dccb2412ac4d0f34b17622d91c1",
geometryHash: "7a3fa92ae1e8"
},
```

My SpeckleGrasshopper.gha build JSON:
```
Xdir: {
type: "Vector",
value: [ -0.865788603160596, 0.5004099265974089, 0 ],
hash: "1fa33dccb2412ac4d0f34b17622d91c1",
geometryHash: "7a3fa92ae1e8"
}
```

Any other ideas?

**Comment by didimitrie** [comment]
Hey @mswaidan! the first one looks correct, whereas the second is wrong... did you pull the latest SpeckleRhino? I remember fixing this, but not testing it, hence the issue is still open...

**Comment by mswaidan** [comment]
@didimitrie Yes, that's building this branch (2 ahead of master): https://github.com/speckleworks/SpeckleRhino/tree/matt/controller

Looks like it may be these lines?
https://github.com/speckleworks/SpeckleCore/blob/53332c9fd2c281a6d16d9e37e7488db8a826c74d/SpeckleCore/ModelObjects.cs#L397-L411

**Comment by didimitrie** [comment]
🤦‍♂️

**Comment by mswaidan** [comment]
I've opened an issue in SpeckleSpecs and can make the changes, but not sure of the workflow after that.
