### ISSUE TITLE
GH Receiver doesn't clear object cache when forcing refresh.

### ISSUE THREAD

**Issue by tsvilans** [speckleworks/SpeckleRhino#168]
#### Expected Behaviour
- GH Receiver component receives object from stream.
- Object is updated (new data uploaded to same objectId)
- GH Receiver is forced to refresh (right-click -> Fore refresh.)
- GH Receiver updates object with new data.

#### Actual Behaviour
- ...
- GH Receiver is forced to refresh.
- GH Receiver does not update object with new data

#### Affected Projects
- SpeckleGrasshopper

#### Reproduction Steps & System Config (win, osx, web, etc.)
Win 7, x64, Rhino 6

#### Proposed Solution (if any)
- Clear object cache for GH Receiver when forcing refresh.

**Comment by didimitrie** [comment]
@tsvilans , you will need to regenerate the hash of the object! Call SetHashes on it with the old + new info, and this should then work out! (check the source ctors in  `Base..Extended..Something.cs`)

**Comment by tsvilans** [comment]
@didimitrie Ok, need to implement this. Currently I'm creating MD5 hashes from the JSON string in Python. This outputs 16- or 32-character hashes (can't remember) and haven't looked at how to make the 12-character ones as you do. Not sure if this will be an issue?

**Comment by didimitrie** [comment]
Gotcha. Re char count, you can just strip the last 4/20 chars, afaik. To google, but i think hashes work that way (you increase your collision chances, but that's a problem for another time). 

The hash update when data is modified part - that's largely an issue up to you and how you handle it in python. In SpeckleCore, I always generate new objects, and the converter (or the constructor) makes sure a new hash is generated. It's a non-enforced, per object, dev-manual step that is critical and i guess will cause problems at one point.

And re generation, it differs from object type to object type (ie points vs planes and stuff) though this is something i would like to abstract away more elegantly in the (not near) future...

**Comment by kylegmaxwell** [comment]
re: Currently I'm creating MD5 hashes from the JSON string in Python
Also you may want to consider that JSON serialization is non deterministic (depending on the library), so if you want the same hash of the same data you need to make sure properties are consistently ordered. Hope this helps.

**Comment by tsvilans** [comment]
@kylegmaxwell Right on, definitely something to pay attention to. At the moment I'm alphabetically ordering the keys when converting to JSON, so hopefully that works for now...

**Comment by didimitrie** [comment]
Imma gonna close this one for now, as it's morphing into a new issue, which so far we didn't need to discuss as we didn't have object generation from outside .net. Discussing this one's going to be fun: 

# Generating consistent hashes for `SpeckleObjects` between .NET, Python, JS, etc. 

Ie The same SpeckleMesh in python should have the same hash its SpeckleMesh counterpart in .NET. 

We can be relaxed on this one for now, as i'm not sure what the exact business case for this would be, though i'm sure it's going to bite us back later on. 

The current tenets are (subject to later change of course, but let's stick with them for now): only forward. no simultaneous edits of the same object or stream from multiple locations. You need to send something back, make a new stream (or object) and send stuff through that. 

The why: concurrent editing is a can on of worms that's been solved for text and not much else. It's a pandora's box of unknown choices for things that mean 1mb+ of meshes and voronois every 500ms over unstable networks 😬
