### ISSUE TITLE
Current Receiver Display ~Sucks~ could be improved.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#178]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
The displayed geometry (Meshes, Breps, Extrusions) from Speckle should look awesome.

#### Actual Behaviour
The displayed geometry from Speckle should looks like 💩 .

#### Affected Projects
Nope. Just SpeckleRhino

#### Reproduction Steps & System Config (win, osx, web, etc.)
- Receive a Mesh, Brep, or Extrusion. 
- Try to like it.
- Fail

#### Proposed Solution (if any)
Tweak until awesome.

**Comment by didimitrie** [comment]
closing as it's >1year now
