### ISSUE TITLE
Small curves render coursely

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleRhino#216]
#### Expected Behaviour
Small curves and large curves should render similarly in the viewer

#### Actual Behaviour
Small curves look chunky

#### Affected Projects
SpeckleViewer

#### Reproduction Steps & System Config (win, osx, web, etc.)
Rhino5 & Rhino6 sender to SpeckleViewer

#### Proposed Solution (if any)
Adjust curve handling in converter.js

**Comment by didimitrie** [comment]
Needs to be controlled in the way we generate the `displayValue` of the nurbs curves in the rhino converter.

**Comment by didimitrie** [comment]
@mswaidan , is this still an issue? I don't remember 😬  I think yes, but is it *really* needed?

**Comment by mswaidan** [comment]
@didimitrie  AFAIK, yes, but since I'm no longer using Speckle for small objects I haven't noticed it. I think we can close and address it if it comes again.
