### ISSUE TITLE
Add "Name" Property to SpeckleObject

### ISSUE THREAD

**Issue by gouldingken** [speckleworks/SpeckleRhino#224]
Step 0: 
- [X] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Proposed Spec Change
Introduce "Name" as a standard property on SpeckleObject and connect this to the RhinoObject.Name property.

**Comment by didimitrie** [comment]
names now exist on the base speckle object. connecting them to the rhino object name is something we should do over in [SpeckleCoreGeometry](https://github.com/speckleworks/SpeckleCoreGeometry), if actually possible.
