### ISSUE TITLE
properties mess within the schemabuilder component

### ISSUE THREAD

**Issue by PaulPoinet** [speckleworks/SpeckleRhino#252]
https://github.com/PaulPoinet/SpeckleRhino/blob/Paul/dev/initobj/SpeckleGrasshopper/UserDataUtils/SchemaBuilderComponent.cs

#### Expected Behaviour
Set properties within the SchemaBuilder component properly

#### Actual Behaviour
What's actually going on!

Code becomes messy 👎 
The code originally took into account quite a few user expectations when considering only the `showAdditionalProps` toggle (preserves existing fields). Adding more features such as `showApplicationId_Only` results in making the code more convoluted.

#### Future steps 💯 
EITHER
- Create a dictionary to keep track of the current properties.
- externalize properties in another component resulting in only one properties field for the schemabuilder component.
- have only two controls: `showApplicationId_Only` and the future dropdown menu to manually select the properties to generate. If one of them is or contains `true`, the properties field disappear.

OR
- Create a dictionary to keep track of the current properties.
- Keep properties internal, along with `showApplicationId_Only` and the future dropdown menu.

**Comment by didimitrie** [comment]
I think this can be closed now
