### ISSUE TITLE
Rhino Receiver Conduit tweaks

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#29]
Give a little love to this...mesh colors, etc.

**Comment by fraguada** [comment]
In R5 this might be annoying since Vertex Colors don't pay attention to Alpha: 
<img width="866" alt="screen shot 2017-12-14 at 20 08 29" src="https://user-images.githubusercontent.com/1014562/34010115-c4127664-e10b-11e7-951b-12087f01efa8.png">
These will occlude other objects and look exactly as they would in a Shaded Display mode if they were baked. 

In Rhino 6, this is not an issue since we can add some alpha to the Vertex Colors. It would theoretically be possible to make a bitmap from the vertex colors and map it to the mesh, but this seems like overkill.

**Comment by didimitrie** [comment]
defs overkill. we keep them as they are now, would say - you've anyway got `DrawBoxCorners` around them when you hover...

**Comment by fraguada** [comment]
Closing then...watch your colors people!
