### ISSUE TITLE
UserDataUtils plugin ???

### ISSUE THREAD

**Issue by jimver04** [speckleworks/SpeckleRhino#323]
Hi,

I have installed Speckle Server locally v2.2.5. Also installed the Rhino and Grasshoper connector. When I open from Rhino 7, the test file for Grasshoper (.gh file found in test folder it says that it needs the 'UserDataUtils' plugin) which however does not exist in Food4Rhino.

Any idea ?

Best,
Dimitrios @ PrismArch project

**Comment by teocomi** [comment]
Hello Dimitrios!

I think there might have been some confusion with our old version of Speckle (v1) and the new one (v2)!
V1 is no longer maintained, so here below links to everything v2 related:

- all the repos are under another github org: https://github.com/specklesystems/
- here's the docs for v2: https://speckle.guide/
- community forum: https://speckle.community/
- website: https://speckle.systems/

Have a look at the guide and install Speckle Manager, with that you'll get our v2 connectors. I presume you are running a v2 server but a v1 connector at the moment and following a v2 tutorial :)

Hope it helps!
Matteo

**Comment by jimver04** [comment]
Hi Matteo,

indeed I was looking at a Speckle v1 example. 

Nevertheless, I have managed to push commits from Rhino and Revit to speckle server (running in docker locally). 

As a second step
I am trying to execute the tutorial steps: https://speckle.guide/user/interop-gh-revit.html 
but I go very slow. 
1. I have done step "Sharing Revit project data" successfully.  
2. I have done also "Using Revit project data" in Rhino. 

I have a question, although the data is fetched in Grasshopper, how do I visualize them in 3D ?

Here I am:
![image](https://user-images.githubusercontent.com/1898502/113411933-b898f280-93bf-11eb-9382-716f29edaa96.png)

![image](https://user-images.githubusercontent.com/1898502/113411480-89ce4c80-93be-11eb-910c-a1689a0f9fbd.png)



Another question is how do I merge two commits ? There is only send or receive but not merge. I have experience with Github.

Best,
Dimitrios

**Comment by teocomi** [comment]
Hey Dimitrios, great that you are following our tutorials! Would you mind posting your question on the [forum](https://speckle.community/c/help/8)?
That's the best place for these questions, in the meantime I'll prepare a reply :)
