### ISSUE TITLE
AppVeyor build artifacts

### ISSUE THREAD

**Issue by pearswj** [speckleworks/SpeckleRhino#34]
Zip up build artifacts so we can provide a link to download the latest successful build from appveyor.

See https://www.appveyor.com/docs/packaging-artifacts/

**Comment by didimitrie** [comment]
Should (can) they be separated into gh plugins and rh plugins?

**Comment by pearswj** [comment]
They can and perhaps they should! As a first pass I was just going to provide an easy way for people to get their hands on the latest build. Later we can think about creating plug-in packages/installers/etc.

**Comment by pearswj** [comment]
Added a link to the README in 8207552. Grasshopper only for now. Ran out of time, driving back to Bath in a sec. But it's a start!

**Comment by fraguada** [comment]
I feel separate packages will create an unnecessary maintenance vector and dup dlls can be avoided. I can investigate the appropriate packaging mechanism to keep everything together.
