### ISSUE TITLE
Add .editorconfig to project to keep formatting consistent

### ISSUE THREAD

**Issue by pearswj** [speckleworks/SpeckleRhino#72]
At McNeel we've been looking into using the new `.editorconfig` support that's baked into Visual Studio 2017 to enforce formatting rules and avoid unnecessary whitespace changes. Perhaps it would be a good idea here too?

* https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options
* [.NET's own `.editorconfig` file](https://github.com/dotnet/roslyn/blob/master/.editorconfig)

**Comment by didimitrie** [comment]
The answer is yes. We need this! I go by a variant of mr doob approves style, at least in js, and close to that in .net.
