### ISSUE TITLE
Phase out Rhino v5 dev.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#74]
Now that Rhino 6 is out, measure dev friction and eventually decide to End Support for Speckle Rhino for Rhino 5. Low priority.

**Comment by didimitrie** [comment]
I would even propose that we use the amazing prowess and outreach of Speckle to promote upgrades to 6... 

So this one  defs has my vote, as long as we nail down #57 ...

**Comment by didimitrie** [comment]
yep. done. some 1.5 years later.
