### ISSUE TITLE
Packaging Issues

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#75]
Getting some errors related to how the RHI is packaged, though I'm not surprised. The package itself should be tidied up. Should figure out how to keep CEF related stuff in a subdirectory. Related to #49. Tested with Rhino 5 sr14 RHI and Rhino 6 RHI.

- [x] RHI is corrupt 
![specklerhinorhi](https://user-images.githubusercontent.com/1014562/35304943-c7a47812-0097-11e8-87fe-524aaad37418.JPG)
[specklerhino (20180123-235255).log](https://github.com/speckleworks/SpeckleRhino/files/1657911/specklerhino.20180123-235255.log)

- [x] RHI GUID Mismatch
![specklerhinorhi2](https://user-images.githubusercontent.com/1014562/35305045-33946c8a-0098-11e8-9e9c-b98a260b5cfb.JPG)
[Release (20180123-235127).log](https://github.com/speckleworks/SpeckleRhino/files/1657910/Release.20180123-235127.log)

**Comment by fraguada** [comment]
https://github.com/cefsharp/CefSharp/pull/1753 this looks handy.

**Comment by pearswj** [comment]
Eek. @fraguada shout if you need a hand!

**Comment by didimitrie** [comment]
This looks really good  👍 even if it doesn't work!!! Sorry for the unhelpful comment...

**Comment by pearswj** [comment]
@fraguada I think I've figured out why the zip archive is corrupted. `7z` must have been confused by the `.rhi` extension. Forcing `7z` to use ZIP compression seems to work. I also added the recursive flag for good measure (doesn't make a difference AFAICT, but the docs says otherwise!).

```
7z a -tzip -r specklerhino.rhi %APPVEYOR_BUILD_FOLDER%\SpeckleRhinoPlugin\SpeckleWinR6\bin\Release\*
7z a -tzip -r specklerhino.rhi %APPVEYOR_BUILD_FOLDER%\SpeckleRhinoPlugin\SpeckleWinR5\bin\Release\*
7z a -tzip -r specklerhino.rhi %APPVEYOR_BUILD_FOLDER%\SpeckleGrasshopper\bin\Release\*
```

Note also I've changed `*.*` to `*`, after reading the following ([source](https://sevenzip.osdn.jp/chm/cmdline/commands/add.htm)):

>_7-Zip doesn't use the system wildcard parser. 7-Zip doesn't follow the archaic rule by which *.* means any file. 7-Zip treats *.* as matching the name of any file that has an extension. To process all files, you must use a * wildcard._

**Comment by pearswj** [comment]
And I guess all the Rhino plug-ins need to have the same GUID!

Yours,

Capitán Obvio

**Comment by pearswj** [comment]
Just tested the release [here](https://ci.appveyor.com/project/SpeckleWorks/specklerhino/build/157/artifacts) and it installed properly for Rhino 5 and Rhino 6!

**Comment by fraguada** [comment]
Artifact RHI installs, and initial tests firing up the plugin works well in Rhino 5 x64, Rhino 6, and GH in both.
