### ISSUE TITLE
R5 .3dm with saved streams open with duplicate streams.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#82]
Open attached file in Rhino 5 and see that it instantiates a duplicate of each stream.
[R5_Receivers.3dm.zip](https://github.com/speckleworks/SpeckleRhino/files/1664012/R5_Receivers.3dm.zip)

**Comment by didimitrie** [comment]
Most probably because of duplicate Interop objects in the background, namely tied to #85 and #84 

Also, going forward, it's good to start with a clean file, if one got messy; I can add a purge duplicates and some defensive code on the .net side too. Hope that file will allow me to reproduce!
