### ISSUE TITLE
Streams not detected when opening R5 3dm in R6 and vice versa.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#83]
No streams are instantiated. Probably due to difference in how R5 and R6 read user data?

Each time, an exception is thrown that that particular assembly isn't loaded. This fails silently in release builds/non debug.

This might be a bug in Rhino.

**Comment by didimitrie** [comment]
think this is because of #86

**Comment by fraguada** [comment]
related to #86, prob a Rhino bug
