### ISSUE TITLE
Browser isn't ready by the time Speckle is.

### ISSUE THREAD

**Issue by fraguada** [speckleworks/SpeckleRhino#84]
1. Create an R6 file with receiver streams
2. Start new file
Result: old streams not purged from preview.

**Comment by didimitrie** [comment]
Dev log: I think it's the events that Interop sets on the rhino `BeginSaveFile`, etc., potentially also touches on #85; they never get removed, leading to being fired three times, or four times, or _n times_, depending on how many file new/save operations you do...

Solution would be to keep the Interop obj, and just replace the browser inside it as 987d5d0 tries, when the panel gets reintialised. Nevertheless, this is not clean, so I think we'll need to have a dispose method on it.

**Comment by didimitrie** [comment]
Log: 
`public SpeckleRhinoUserControl( )` is created every time R6 opens a new file. no idea how/where the old one is disposed of, but now forcing disposals on the Interop object in `BeginOpenDocument`.

Now R5 of course just crashes outright on initialisation...
