### ISSUE TITLE
Pimp up readme ✨

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleRhino#96]
- screenshots of the plugins, preferably a fancy image or something or even a gif
- big friendly download button

**Comment by fraguada** [comment]
![image](https://user-images.githubusercontent.com/1014562/40281319-9c1fa318-5c60-11e8-9208-92fbc126095d.png)

This is a fine image ^

**Comment by didimitrie** [comment]
😊 🙇

**Comment by fraguada** [comment]
I'd say it is pimped enough for the time being.
