### ISSUE TITLE
Receiver disconnects output node

### ISSUE THREAD

**Issue by dradomtsev** [speckleworks/SpeckleRhino#98]
I don't know is it a bug but when You connecting other ID to the same Receiver it disconnects output node
![screenrecorderproject26](https://user-images.githubusercontent.com/33149174/35621764-329590e2-068e-11e8-95aa-610c3f6e2896.gif)

**Comment by didimitrie** [comment]
Thanks for filing this! Unfortunately it's a pain to deal with how grasshopper handles creation of outputs, and how they're connected with the rest of the components. 

The  "A" input from the first stream is different than the "A" in the second one (by `guid` not by name!), therefore the disconnect. I'm always dong a diff by original input's guid, and this is how i keep track of what's going on, what needs to be added/replaced. I can't do it by names, as you can have theoretically to inputs/outputs named "A" on the same stream...

I'll leave this  one here, and label it as an enhancement, not bug 👍

**Comment by didimitrie** [comment]
I'm going to  mark this as closed, as this is expected behaviour - guids differ, and i don't want to do a messy name based diff on layers, as it might cause more troubles down the line...
